import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import test from 'node:test'

const root = fileURLToPath(new URL('../../', import.meta.url))
const checker = join(root, 'scripts/git/check-commit-message.mjs')
const installer = join(root, 'scripts/git/install-hooks.mjs')
const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => !key.startsWith('GIT_')))
Object.assign(env, { GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null' })

function fixture(t) {
  const directory = mkdtempSync(join(tmpdir(), 'portfolio-commit-policy-'))
  t.after(() => rmSync(directory, { recursive: true, force: true }))
  return directory
}

function run(command, args, cwd) {
  const result = spawnSync(command, args, { cwd, env, encoding: 'utf8' })
  assert.ifError(result.error)
  return result
}

function repository(t) {
  const directory = fixture(t)
  assert.equal(run('git', ['init', '--quiet'], directory).status, 0)
  const destination = join(directory, 'scripts/git/check-commit-message.mjs')
  mkdirSync(dirname(destination), { recursive: true })
  copyFileSync(checker, destination)
  return directory
}

function check(directory, message) {
  const path = join(directory, 'message')
  writeFileSync(path, message)
  const result = run(process.execPath, [checker, path], directory)
  assert.equal(readFileSync(path, 'utf8'), message, '검사는 메시지를 변경하지 않아야 함')
  return result.status
}

test('일반 메시지·사람 공동 작성·도구 설명 허용', (t) => {
  const directory = fixture(t)
  for (const message of [
    '포트폴리오 초기 구성\n',
    '기능 수정\n\nCo-Authored-By: Mina Kim <mina@example.com>\n',
    'docs: Claude와 Codex 사용 지침 수정\n\nCo-Authored-By 검사 규칙을 추가함\n',
  ]) assert.equal(check(directory, message), 0)
})

test('도구 트레일러·CRLF·자동 생성 서명 차단', (t) => {
  const directory = fixture(t)
  for (const message of [
    '수정\n\nCo-Authored-By: Claude Opus <noreply@anthropic.com>\n',
    '수정\r\n\r\nco-authored-by: CODEX <noreply@openai.com>\r\n',
    '수정\n\nCo-Authored-By: Assistant <noreply@openai.com>\n',
    '수정\n\nGenerated by Codex\n',
    '수정\n\n🤖 Generated with [Claude Code](https://example.com)\n',
    '수정\n\n공동 작성: Codex\n',
    '수정\n\nClaude와 함께 작성\n',
  ]) assert.equal(check(directory, message), 1, message)
})

test('메시지 파일 오류는 실패로 처리', (t) => {
  const directory = fixture(t)
  assert.equal(run(process.execPath, [checker], directory).status, 1)
  assert.equal(run(process.execPath, [checker, join(directory, 'missing')], directory).status, 1)
})

test('설치 후 Git이 훅 실행, 재설치에도 백업 중복 없음', (t) => {
  const directory = repository(t)
  assert.equal(run(process.execPath, [installer], directory).status, 0)
  const hook = join(directory, '.git/hooks/commit-msg')
  assert.ok(statSync(hook).mode & 0o111)
  const original = readFileSync(hook, 'utf8')
  assert.equal(run(process.execPath, [installer], directory).status, 0)
  assert.equal(readFileSync(hook, 'utf8'), original)
  assert.equal(existsSync(`${hook}.before-portfolio`), false)
  const message = join(directory, 'message')
  writeFileSync(message, '일반 커밋\n')
  assert.equal(run('git', ['hook', 'run', 'commit-msg', '--', message], directory).status, 0)
  writeFileSync(message, '수정\n\nCo-Authored-By: Codex <noreply@openai.com>\n')
  assert.equal(run('git', ['hook', 'run', 'commit-msg', '--', message], directory).status, 1)
})

test('기존 훅 보존, 기존 훅이 추가한 자동 서명도 검사', (t) => {
  const directory = repository(t)
  const hook = join(directory, '.git/hooks/commit-msg')
  const old = '#!/bin/sh\nprintf "\\nGenerated by Codex\\n" >> "$1"\n'
  writeFileSync(hook, old, { mode: 0o755 })
  const other = join(directory, '.git/hooks/pre-commit')
  writeFileSync(other, '#!/bin/sh\nexit 0\n', { mode: 0o755 })
  assert.equal(run(process.execPath, [installer], directory).status, 0)
  assert.equal(readFileSync(`${hook}.before-portfolio`, 'utf8'), old)
  assert.equal(readFileSync(other, 'utf8'), '#!/bin/sh\nexit 0\n')
  const message = join(directory, 'message')
  writeFileSync(message, '일반 커밋\n')
  assert.equal(run('git', ['hook', 'run', 'commit-msg', '--', message], directory).status, 1)
})

test('기존 훅의 실패 상태 유지', (t) => {
  const directory = repository(t)
  writeFileSync(join(directory, '.git/hooks/commit-msg'), '#!/bin/sh\nexit 7\n', { mode: 0o755 })
  assert.equal(run(process.execPath, [installer], directory).status, 0)
  const message = join(directory, 'message')
  writeFileSync(message, '일반 커밋\n')
  assert.equal(run('git', ['hook', 'run', 'commit-msg', '--', message], directory).status, 7)
})

test('커스텀 훅 설정을 덮어쓰지 않음', (t) => {
  const directory = repository(t)
  assert.equal(run('git', ['config', 'core.hooksPath', '.custom-hooks'], directory).status, 0)
  assert.equal(run(process.execPath, [installer], directory).status, 1)
  assert.equal(run('git', ['config', '--get', 'core.hooksPath'], directory).stdout.trim(), '.custom-hooks')
  assert.equal(existsSync(join(directory, '.git/hooks/commit-msg')), false)
})

test('기존 훅과 백업 충돌 시 두 파일 보존', (t) => {
  const directory = repository(t)
  const hook = join(directory, '.git/hooks/commit-msg')
  writeFileSync(hook, 'current')
  writeFileSync(`${hook}.before-portfolio`, 'backup')
  assert.equal(run(process.execPath, [installer], directory).status, 1)
  assert.equal(readFileSync(hook, 'utf8'), 'current')
  assert.equal(readFileSync(`${hook}.before-portfolio`, 'utf8'), 'backup')
})
